Adds an optional `--enable-volume` to the generate-docker command
pendulum-chain/pendulum-launch pull request #25
Opened 2022-03-21 08:23 UTC by xiuxiu62

This adds a docker volume for shared specs within inner nodes.  When enabled, the program will create and populate a volume, mount the volume to provided nodes, and launch those nodes with the available volume.

2022-03-21 15:29 UTC, gonzamontiel requested changes

2022-03-21 15:29 UTC, gonzamontiel commented on docker-compose.yml
> +version: "3.2"
Is this file an example? If that's the case I would move the contents to the README, indicating that this is an expected output (given certain input). Alternatively, move the launch.json and this file to a folder called `samples`.

2022-03-23 10:06 UTC, gonzamontiel approved these changes
Looking good!

2022-03-23 10:27 UTC, merged

2022-03-23 10:28 UTC, xiuxiu62 commented
Reminder for me to update the Cargo.toml version and README/gitbook docs